name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test - ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["pypy-3.7", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run tests
        run: python -m tox -e py
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run linting
        run: python -m tox -e pep8
      - name: Run mypy
        run: python -m tox -e mypy
  packaging:
    name: Packaging
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: python -m pip install tox
      - name: Test packaging
        run: python -m tox -e packaging
